import "../comstyles/component.css";

export const usercolumns = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "firstName", headerName: "First Name", width: 120 },
  { field: "lastName", headerName: "Last Name", width: 120 },
  { field: "dob", headerName: "Date of Birth", width: 100 },
  { field: "phone_number", headerName: "Phone Number", width: 120 },
  { field: "email", headerName: "Email", width: 120 },
  { field: "role", headerName: "Role", width: 100 },
  { field: "createdAt", headerName: "Created At", width: 100 },
  { field: "updatedAt", headerName: "Updated At", width: 100 },
];

export const riskreviewcolumn = [
  {
    label: "Risk Name",
    field: "RiskName",
    width: 200,
  },
  {
    label: "Risk Owner",
    field: "RiskOwner",
    width: 150,
  },
  {
    label: "Mitigatioin Effort",
    field: "MitigationEffort",
    width: 150,
  },
  {
    label: "Impact Score",
    field: "ImpactScore",
    width: 100,
  },
  {
    label: "Possibility Score",
    field: "ProbabilityScore",
    width: 100,
  },
  {
    label: "Risk Score",
    field: "RiskScore",
    width: 100,
  },
  {
    label: "Action",
    field: "Action",
    width: 100,
  },
];

export const riskreviewrow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
    Action: "Review",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
    Action: "Review",
  },
  {
    id: 7,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 8,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 9,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
    Action: "Review",
  },
  {
    id: 10,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 11,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 12,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
    Action: "Review",
  },
];

export const riskmitigationcolumn = [
  {
    label: "Risk Name",
    field: "RiskName",
    width: 200,
  },
  {
    label: "Risk Owner",
    field: "RiskOwner",
    width: 150,
  },
  {
    label: "Mitigatioin Effort",
    field: "MitigationEffort",
    width: 150,
  },
  {
    label: "Impact Score",
    field: "ImpactScore",
    width: 100,
  },
  {
    label: "Possibility Score",
    field: "ProbabilityScore",
    width: 100,
  },
  {
    label: "Risk Score",
    field: "RiskScore",
    width: 100,
  },
  {
    label: "Action",
    field: "Action",
    width: 100,
  },
];

export const riskmitigationrow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
    Action: "Review",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
    Action: "Review",
  },
  {
    id: 7,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 8,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 9,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
    Action: "Review",
  },
  {
    id: 10,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 11,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
    Action: "Review",
  },
  {
    id: 12,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
    Action: "Review",
  },
];

export const reportriskmitigationcolumn = [
  {
    label: "Risk Name",
    field: "RiskName",
    width: 200,
  },
  {
    label: "Risk Owner",
    field: "RiskOwner",
    width: 150,
  },
  {
    label: "Mitigatioin Effort",
    field: "MitigationEffort",
    width: 200,
  },
  {
    label: "Date",
    field: "Date",
    width: 100,
  },
  {
    label: "Risk Score",
    field: "RiskScore",
    width: 100,
  },
];

export const reportriskmitigationrow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 7,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 8,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 9,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 10,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 11,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 12,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
];

export const reportopenrisktoreviewcolumn = [
  {
    label: "Risk Name",
    field: "RiskName",
    width: 200,
  },
  {
    label: "Risk Owner",
    field: "RiskOwner",
    width: 150,
  },
  {
    label: "Mitigatioin Effort",
    field: "MitigationEffort",
    width: 200,
  },
  {
    label: "Date",
    field: "Date",
    width: 100,
  },
  {
    label: "Risk Score",
    field: "RiskScore",
    width: 100,
  },
];

export const reportopenrisktoreviewrow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 7,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 8,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 9,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 10,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 11,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 12,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
];

export const reportopenriskassignedtomecolumn = [
  {
    label: "Risk Name",
    field: "RiskName",
    width: 200,
  },
  {
    label: "Risk Owner",
    field: "RiskOwner",
    width: 150,
  },
  {
    label: "Mitigatioin Effort",
    field: "MitigationEffort",
    width: 200,
  },
  {
    label: "Date",
    field: "Date",
    width: 100,
  },
  {
    label: "Risk Score",
    field: "RiskScore",
    width: 100,
  },
];

export const reportopenriskassignedtomerow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 7,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 8,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 9,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 10,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 11,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 12,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
];

export const reportriskandcontrolecolumn = [
  {
    label: "Risk Name",
    field: "RiskName",
    width: 200,
  },
  {
    label: "Risk Owner",
    field: "RiskOwner",
    width: 150,
  },
  {
    label: "Mitigatioin Effort",
    field: "MitigationEffort",
    width: 200,
  },
  {
    label: "Date",
    field: "Date",
    width: 100,
  },
  {
    label: "Risk Score",
    field: "RiskScore",
    width: 100,
  },
];

export const reportriskandcontrolerow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 7,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 8,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 9,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 10,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 11,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 12,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
];

export const reportaudittrailcolumn = [
  {
    label: "Risk Name",
    field: "RiskName",
    width: 200,
  },
  {
    label: "Risk Owner",
    field: "RiskOwner",
    width: 150,
  },
  {
    label: "Mitigatioin Effort",
    field: "MitigationEffort",
    width: 200,
  },
  {
    label: "Date",
    field: "Date",
    width: 100,
  },
  {
    label: "Risk Score",
    field: "RiskScore",
    width: 100,
  },
];

export const reportaudittrailrow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 7,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 8,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 9,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
  {
    id: 10,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 11,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    Date: "23/04/2009",
    RiskScore: "2",
  },
  {
    id: 12,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    Date: "23/04/2009",
    RiskScore: "4",
  },
];

export const deptcolumn = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "deptID", headerName: "Dapartment ID", width: 120 },
  { field: "name", headerName: "Name", width: 120 },
  { field: "createdAt", headerName: "Created At", width: 100 },
  { field: "updatedAt", headerName: "Updated At", width: 120 },
];

export const sidebarcolumn = [
  {
    label: "Risk Name",
    field: "RiskName",
    width: 150,
  },
  {
    label: "Risk Score",
    field: "RiskScore",
    width: 100,
  },
];

export const sidebarrow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskScore: "2",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskScore: "2",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskScore: "4",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskScore: "2",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskScore: "2",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskScore: "4",
  },
  {
    id: 7,
    RiskName: "Health Risk",
    RiskScore: "4",
  },
  {
    id: 8,
    RiskName: "Transportation",
    RiskScore: "2",
  },
  {
    id: 9,
    RiskName: "IT Risk",
    RiskScore: "2",
  },
];

export const riskmonitoringcolumn = [
  { field: "id", headerName: "ID", width: 70 },
  {
    field: "risk_response_activitiy_status",
    headerName: "Risk Activity",
    width: 120,
  },
  {
    field: "risk_response_implementation",
    headerName: "Risk Implementation",
    width: 120,
  },
  { field: "challenges", headerName: "Challenges", width: 100 },
  { field: "comments", headerName: "Comments", width: 120 },
  { field: "createdAt", headerName: "Created At", width: 120 },
];
export const riskappetitereportgreatercolumn = [
  {
    label: "Risk Name",
    field: "RiskName",
    width: 100,
  },
  {
    label: "Risk Owner",
    field: "RiskOwner",
    width: 400,
  },
  {
    label: "Mitigatioin Effort",
    field: "MitigationEffort",
    width: 200,
  },
];

export const riskappetitereportgreaterrow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
  },
  {
    id: 7,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
  },
  {
    id: 8,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
  },
  {
    id: 9,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
  },
  {
    id: 10,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
  },
  {
    id: 11,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
  },
  {
    id: 12,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
  },
];

export const riskappetitereportlowercolumn = [
  {
    label: "Risk Name",
    field: "RiskName",
    width: 100,
  },
  {
    label: "Risk Owner",
    field: "RiskOwner",
    width: 400,
  },
  {
    label: "Mitigatioin Effort",
    field: "MitigationEffort",
    width: 200,
  },
];

export const riskappetitereportlowerrow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
  },
  {
    id: 7,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
  },
  {
    id: 8,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
  },
  {
    id: 9,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
  },
  {
    id: 10,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
  },
  {
    id: 11,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
  },
  {
    id: 12,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
  },
];

export const riskviewcolumn = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "riskID", headerName: "Risk ID", width: 120 },
  { field: "risk_name", headerName: "Risk Name", width: 120 },
  { field: "risk_description", headerName: "Risk Description", width: 100 },
  { field: "risk_category", headerName: "Risk Category", width: 120 },
  { field: "risk_impact_level", headerName: "Risk Impact Level", width: 70 },
  { field: "risk_score", headerName: "Risk Score", width: 100 },
  { field: "risk_owner", headerName: "Risk Owner", width: 120 },
];

export const riskviewrow = [
  {
    id: 1,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
  },
  {
    id: 2,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
  },
  {
    id: 3,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
  },
  {
    id: 4,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
  },
  {
    id: 5,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
  },
  {
    id: 6,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
  },
  {
    id: 7,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
  },
  {
    id: 8,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
  },
  {
    id: 9,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
  },
  {
    id: 10,
    RiskName: "Transportation",
    RiskOwner: "Manager",
    MitigationEffort: "Travel by air",
    ImpactScore: "4",
    ProbabilityScore: "3",
    RiskScore: "2",
  },
  {
    id: 11,
    RiskName: "IT Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Install Antivirus",
    ImpactScore: "1",
    ProbabilityScore: "4",
    RiskScore: "2",
  },
  {
    id: 12,
    RiskName: "Health Risk",
    RiskOwner: "Manager",
    MitigationEffort: "Routin medical checkup",
    ImpactScore: "1",
    ProbabilityScore: "3",
    RiskScore: "4",
  },
];
